### ISSUE TITLE
As an Open Data Hub manager I would like to promote the routing API EFA of STA by doing a proxy of the domain

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.api.mobility-ninja#29]
Documentation of the EFA API: 
http://daten.buergernetz.bz.it/dataset/southtyrolean-public-transport

Expected behavior: 
http://efa.sta.bz.it/apb/XML_TRIP_REQUEST2 
becomes
mobility.api.opendatahub.bz.it/v2/XML_TRIP_REQUEST2

This should apply to all methods and API calls supported by the EFA API

**Comment by dulvui** [comment]
@rcavaliere It works now on testingmachine
https://mobility.api.opendatahub.testingmachine.eu/v2/XML_TRIP_REQUEST2
If everything is fine we can also set it in production

**Comment by rcavaliere** [comment]
@dulvui many thanks. Yes, works as expected!

Please do this for all methods exposed by EFA, namely:

- [ ] http://efa.sta.bz.it/apb/XML_STOPFINDER_REQUEST
- [ ] http://efa.sta.bz.it/apb/XML_DM_REQUEST
- [ ] http://efa.sta.bz.it/apb/XML_STT_REQUEST
- [ ] http://efa.sta.bz.it/apb/XML_ADDINFO_REQUEST

Please consider that the request to the API can be vary configurable, as you can read here: https://data.civis.bz.it//dataset/575f7455-6447-4626-a474-0f93ff03067b/resource/c4e66cdf-7749-40ad-bcfd-179f18743d84/download/dokumentationxmlschnittstelleapbv32014-08-28.pdf

Are we manage to support all these kind of requests?

**Comment by dulvui** [comment]
@rcavaliere I created now all other methods aswell:
 - https://mobility.api.opendatahub.testingmachine.eu/v2/XML_STOPFINDER_REQUEST
 - https://mobility.api.opendatahub.testingmachine.eu/v2/XML_DM_REQUEST
 - https://mobility.api.opendatahub.testingmachine.eu/v2/XML_STT_REQUEST
 - https://mobility.api.opendatahub.testingmachine.eu/v2/XML_ADDINFO_REQUEST

The request should works as expected because we forward all parameters to STA endpoint.
But I was not able to test specific requests because the documentation is quite big and I din't find example calls, I only checked if the endpoint gives the same default response as the STA endpoint.
Do you have some example calls I can try?

**Comment by dulvui** [comment]
@rcavaliere I added also  https://mobility.api.opendatahub.testingmachine.eu/v2/XML_COORD_REQUEST now and test all your examples by simply replacing https://efa.sta.bz.it/web/ with https://mobility.api.opendatahub.testingmachine.eu/v2/ and it all give the same result. But this is now working only on testingmachine.
Should we implement it also in production with https://mobility.api.opendatahub.com/v2 before closing the task?

**Comment by rcavaliere** [comment]
Yes of course, I put the task in the "Release on Production" lane

**Comment by dulvui** [comment]
@rcavaliere It is now also live in production on mobility.api.opendatahub.com
- https://mobility.api.opendatahub.com/v2/XML_STOPFINDER_REQUEST
- https://mobility.api.opendatahub.com/v2/XML_DM_REQUEST
- https://mobility.api.opendatahub.com/v2/XML_STT_REQUEST
- https://mobility.api.opendatahub.com/v2/XML_ADDINFO_REQUEST
= https://mobility.api.opendatahub.com/v2/XML_COORD_REQUEST
