### ISSUE TITLE
As Projektionisten I would like to have an alternative for the HTTP refererrer, so that we can track the usage of the mobility API on suedtirolmobil channels

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.api.mobility-ninja#38]
Reference issue: https://issues.opendatahub.com/Ticket/Display.html?id=14114

**Comment by ohnewein** [comment]
Time-Series API should implement the same parameters as Content API.

**Comment by clezag** [comment]
Implemented on ninja API, now up in testing.

Both `referer` and `Referer` are allowed.
This is because Content API uses uppercase, but all other mobility parameters are lowercase.

@RudiThoeni will implement lowercase support as well, so both APIs behave the same. 

- [ ] Decide on if we want to advertise this feature in swagger (currently it's not - only in testing) and update the documentation [here](https://github.com/noi-techpark/odh-docs/wiki/Http-Referer) accordingly
- [ ] Notify customer care about issue status, and possibly have them update relevant documentation
- [ ] Add some clarification to timeseries swagger about what `referer` and `origin` do and how they differ

**Comment by clezag** [comment]
We decided that this will not be documented in swagger, but only in the wiki.
The reasoning is that we don't want this to be misused, son only people who absolutely need it should use this feature.
Both lowercase and uppercase will be supported.

**Comment by clezag** [comment]
I've updated the documentation here and removed the swagger documentation of the feature:
https://github.com/noi-techpark/odh-docs/wiki/Http-Referer

**Comment by rcavaliere** [comment]
@clezag good, I have given indication to the Customer Care to reply to the ticket. I think we can close the user story here.
